---
layout: post
title: The Importance of the Trusted Display and Secure Execution
author: Charles Guillemet
summary: Why Trusted Display is a fundamental building block of cryptocurrency wallets by Charles Guillemet
featured-img: nano-confirm
categories: Vault
---
# The Importance of the Trusted Display and Secure Execution

We have all seen the horror stories on Reddit and Twitter, where unfortunate individuals and companies were unwittingly parted with their digital assets after falling victim to an increasingly sophisticated array of malware and phishing attacks.  

Unlike the regular hacks suffered by centralized platforms such as cryptocurrency exchanges—through which at least 282.6M USD was stolen in 2019 (cf. [Chainalysis (1)](#1))—very little is known about the global magnitude of losses incurred as a result of successful attacks on other wallet owners, such as users of third-party wallets which provide ownership of the private keys. 

However, with the ruckus these attacks cause on social media, one can only assume that the total amount stolen exceeds that lost as a result of attacks on centralized platforms. As we will now see, the narrative behind these attacks is usually remarkably consistent from case to case, and can be avoided using simple security measures. 

## What You See Is What You Sign (WYSIWYS)

In this post, we will cover some of the most common threats people and businesses operating a cryptocurrency wallet can be exposed to when they interact with sensitive data, and discuss how a trusted user interface (TUI) can be used to mitigate operational risks. 

When transacting with cryptocurrencies, both individuals and businesses typically need to handle or provide sensitive data as part of the transaction creation process. This step presents the easiest attack point for hackers, since it is often a relatively simple task to display falsified information to the wallet end user or simulate user input to create an unauthorized transaction. 

In the context of managing digital assets, an untrusted user interface allows the attacker to leverage several spoofing threat vectors, including:

### Spoofing the recipient address

Typically the most trivial attack vector to exploit, spoofing the recipient address can allow an attacker to dupe a victim into sending funds to an unexpected address. The attack flow usually goes something like this: 

Alice wants to send some Bitcoin (BTC) to Bob's address and carefully verifies Bob's address before sending her coins. On an *untrusted* display, the attacker (let’s call her Eve) is able to switch the address to which the funds are actually sent, despite displaying the correct address to Alice. As such, while Alice thinks she is sending funds to Bob, the funds are actually sent to the attacker. 
<center>
<img src="/assets/trusted_display/recipient_spoofing.png" style="width:800px;">
</center>  

This kind of spoofing attack can be trivial to implement on a desktop computer or mobile wallet app and there is no reliable way to protect against this kind of attack without the use of a trusted display. Instead, the usual way to detect and prevent such an attack is with a penny test—sending a small amount to Bob’s address before making a larger transaction. 

However, this would only prevent a systematic address swap attack, since a clever attacker could decide to only swap the address in the second transaction.



### Spoofing receiving addresses

The principle behind this attack resembles the previous one—except the fault instead lies with Bob this time. 

In this case, Bob wants to receive funds from Alice, and sends her his address. Sharing the address securely poses a challenge in and of itself, since it can often be intercepted and changed throughout this process. Likewise, in a context where an attacker controls Bob’s wallet, malware could be used to swap Bob’s actual receiving address to one owned by the attacker, which Bob would then send to Alice thinking it was his own address—since it was seemingly generated by his own wallet client. 

<center>
<img src="/assets/trusted_display/receiving_spoofing.png" style="width:800px;">
</center>  

This attack vector can be mitigated by always using the same address, but this can raise privacy concerns since anybody can monitor the address on the public ledger, while some blockchains simply do not support address reuse. 

### Spoofing the approval requests

Digital asset custody solutions that lack a trusted display are generally prime targets for attackers, since they can often be manipulated to trick the user in a variety of ways. Among these, it can be possible to spoof the authorization of transactions, change the addresses associated with wallet contacts, and even bypass additional security measures. 

Although approval requests can be spoofed by a variety of malware types, this most commonly occurs after downloading malware-laden wallet apps or through the unwitting installation of a remote administration tool (RAT). 

### Leveraging user rights

Other attacks seek to leverage user inputs to trick users into revealing potentially sensitive information or authorizing actions that they are not aware of. Clickjacking is one of the most common methods used to accomplish this. 

The principle behind clickjacking is simple. The attacker modifies or authors a user interface (UI) that a target interacts with and uses this to trick the target into clicking or interacting with something either disguised as something else or invisible to the user (an overlay). This can cause users to unknowingly give consent to actions, download malware, or even provide their password or other sensitive credentials to the attacker. 

These threat vectors are considered low hanging fruits for attackers since they are simple to implement and can scale easily. On the other hand, mitigating these attacks is no easy task. 

## The Need for a Trusted User Interface

Here at Ledger, we developed a unique hardware-based trusted user interface that enables users to be absolutely certain that their critical operations have not been tampered with prior to authorization. 

## What is a Trusted User Interface? 

A trusted UI provides a path between the user and the application that is unambiguously free from any form of manipulation. In practice, the Ledger TUI enables users to: 

- Display transaction summaries
- Validate information, including keys and addresses
- Authenticate or validate actions using a PIN or password

In order to ensure a user interface is truly trusted, one must rely on something known as a secure execution environment. This secure execution environment provides two fundamental security features: confidentiality and integrity of the code flow. 

Confidentiality is essential when interacting with digital assets, since it allows the system to protect the cryptographic secrets, while integrity ensures that the code running on the device is the one intended by the developer. 

<center>
<img src="/assets/trusted_display/se_blue.png" style="width:500px;">
</center>  
_<center>The secure element pilots the screen display</center>_

Ledger personal security devices (PSDs) are built around a secure element—a type of tamperproof dedicated circuit that is specifically designed for security. These secure elements are typically found in passports, bank cards and more, and can store a range of information, including biometric information, financial details, and in the case of Ledger’s PSDs—private keys.  

The threat model of secure elements includes even high potential hackers that may have direct access to the chip, with a range of safeguards being included to protect against typical attacks. These circuits go through a third-party security evaluation process, after which they are provided a graded security certificate by a security certification body.

Secure elements offer a secure execution environment with very few interfaces, ensuring the attack surface is minimized. The manufacturing of these chips is strictly controlled and audited, as is their distribution to hardware manufacturers—preventing supply chain attacks.

Ledger secure elements are manufactured and feature a secure loader which allows Ledger to securely load its proprietary operating system (OS) to the chip. Only Ledger can load code onto these circuits. This OS (known as BOLOS) is dedicated for security and offers only the bare minimum of functions to ensure the secure element can perform its main task. 

Ledger’s secure element provide several guarantees:

* High-quality Randomness
* Authenticity and integrity of the device
* User authentication
* Integrity of the apps running on the OS
* Interaction with a trusted display

## Final Word

In this article, we have emphasised the importance of a trusted display and discussed how it relies on a secure execution environment to provide the security guarantees necessary to safely manage cryptographic keys. 

In a future post, I will discuss secure execution environments in more depth and address some of the pitfalls seen in alternative implementations. Stay tuned!

{% include signatures/charles.html %}

#### References

1. <a name="1"></a> [The 2020 state of crypto crime - chainalysis](https://go.chainalysis.com/rs/503-FAP-074/images/2020-Crypto-Crime-Report.pdf )
